## Learn more about services, parameters and containers at
## http://symfony.com/doc/current/service_container.html
#parameters:
#    #parameter_name: value
#
services:
#    demo.listener.login:
#        class: MainBundle\EventListener\LoginListener
#        arguments: ['@router', '@security.authorization_checker', '@eve']
#        tags:
#              - {name: kernel.event_listener, event: 'security.interactive_login', method: onSecurityInteractiveLogin}
    demo.login_success_handler:
         class: MainBundle\EventListener\LoginSuccessHandler
         arguments: ['@router', '@security.authorization_checker']

