<?php

namespace MainBundle\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{
    public function isHotelExist($externalId)
    {
        $query = $this->createQueryBuilder('h')
            ->where('h.externalId = :externalId')
            ->setParameters(['externalId' => $externalId])
            ->getQuery()
            ->getResult();

        return $query;
    }

    public function findExternalId()
    {
        $query = $this->createQueryBuilder('h')
            ->select('h.externalId')
            ->getQuery()
            ->getArrayResult();

        return $query;
    }

    public function deleteId($arrayDiff)
    {

    }
}
