<?php

namespace MainBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findHotelLocations($hotelId)
    {

        $query = $this->createQueryBuilder('l')
            ->where('l.hotel = :hotelId')
            ->setParameters(['hotelId' => $hotelId])
            ->getQuery()
            ->getResult();

        return $query;
    }
}
