<?php

namespace MainBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllHotelUsers($hotelId)
    {
      /* $query = $this->createQueryBuilder('uh')
            ->join('uh.users', 'fu')
            ->where('uh.hotels = :hotelId')
            ->setParameters(['hotelId' => $hotelId])
            ->getQuery()
            ->getResult();

        return $query;*/
    }
}
