MainBundle\Entity\Location:
    properties:
        locationName:
            - NotBlank: ~
        url:
            - NotBlank: ~
            - Regex:
                pattern: '/^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]$/'
                htmlPattern: false
